/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRestaurantsRouteImport } from './routes/_app.restaurants'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppMenuManagerRouteImport } from './routes/_app.menu-manager'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppDebugPedidosRouteImport } from './routes/_app.debug-pedidos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBuscarLojaRouteImport } from './routes/_app.buscar-loja'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantsRoute = AppRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuManagerRoute = AppMenuManagerRouteImport.update({
  id: '/menu-manager',
  path: '/menu-manager',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugPedidosRoute = AppDebugPedidosRouteImport.update({
  id: '/debug-pedidos',
  path: '/debug-pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarLojaRoute = AppBuscarLojaRouteImport.update({
  id: '/buscar-loja',
  path: '/buscar-loja',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/automations': typeof AppAutomationsRoute
  '/buscar-loja': typeof AppBuscarLojaRoute
  '/dashboard': typeof AppDashboardRoute
  '/debug-pedidos': typeof AppDebugPedidosRoute
  '/integrations': typeof AppIntegrationsRoute
  '/menu-manager': typeof AppMenuManagerRoute
  '/orders': typeof AppOrdersRoute
  '/reports': typeof AppReportsRoute
  '/restaurants': typeof AppRestaurantsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/automations': typeof AppAutomationsRoute
  '/buscar-loja': typeof AppBuscarLojaRoute
  '/dashboard': typeof AppDashboardRoute
  '/debug-pedidos': typeof AppDebugPedidosRoute
  '/integrations': typeof AppIntegrationsRoute
  '/menu-manager': typeof AppMenuManagerRoute
  '/orders': typeof AppOrdersRoute
  '/reports': typeof AppReportsRoute
  '/restaurants': typeof AppRestaurantsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/buscar-loja': typeof AppBuscarLojaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debug-pedidos': typeof AppDebugPedidosRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/menu-manager': typeof AppMenuManagerRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/restaurants': typeof AppRestaurantsRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/register'
    | '/admin'
    | '/automations'
    | '/buscar-loja'
    | '/dashboard'
    | '/debug-pedidos'
    | '/integrations'
    | '/menu-manager'
    | '/orders'
    | '/reports'
    | '/restaurants'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/register'
    | '/admin'
    | '/automations'
    | '/buscar-loja'
    | '/dashboard'
    | '/debug-pedidos'
    | '/integrations'
    | '/menu-manager'
    | '/orders'
    | '/reports'
    | '/restaurants'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/checkout'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/automations'
    | '/_app/buscar-loja'
    | '/_app/dashboard'
    | '/_app/debug-pedidos'
    | '/_app/integrations'
    | '/_app/menu-manager'
    | '/_app/orders'
    | '/_app/reports'
    | '/_app/restaurants'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurants': {
      id: '/_app/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof AppRestaurantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu-manager': {
      id: '/_app/menu-manager'
      path: '/menu-manager'
      fullPath: '/menu-manager'
      preLoaderRoute: typeof AppMenuManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug-pedidos': {
      id: '/_app/debug-pedidos'
      path: '/debug-pedidos'
      fullPath: '/debug-pedidos'
      preLoaderRoute: typeof AppDebugPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buscar-loja': {
      id: '/_app/buscar-loja'
      path: '/buscar-loja'
      fullPath: '/buscar-loja'
      preLoaderRoute: typeof AppBuscarLojaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppBuscarLojaRoute: typeof AppBuscarLojaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebugPedidosRoute: typeof AppDebugPedidosRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppMenuManagerRoute: typeof AppMenuManagerRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRestaurantsRoute: typeof AppRestaurantsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppBuscarLojaRoute: AppBuscarLojaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebugPedidosRoute: AppDebugPedidosRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppMenuManagerRoute: AppMenuManagerRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReportsRoute: AppReportsRoute,
  AppRestaurantsRoute: AppRestaurantsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
